In [8]:
# prompt: [
#     [-1, -1, -1, -1,  0, -1],
#     [-1, -1, -1,  0, -1, 100],
#     [-1, -1, -1,  0, -1, -1],
#     [-1,  0,  0, -1,  0, -1],
#     [ 0, -1, -1,  0, -1, 100],
#     [-1,  0, -1, -1,  0, 100]
# ]
# 針對以上的Reward Matrix 執行Q-learning,起點為S3(表示R(2)),出口為S6(表R5),以產生最佳路徑

import numpy as np

# Reward matrix
R = np.array([
    [-1, -1, -1, -1,  0, -1],
    [-1, -1, -1,  0, -1, 100],
    [-1, -1, -1,  0, -1, -1],
    [-1,  0,  0, -1,  0, -1],
    [ 0, -1, -1,  0, -1, 100],
    [-1,  0, -1, -1,  0, 100]
])
R





array([[ -1,  -1,  -1,  -1,   0,  -1],
       [ -1,  -1,  -1,   0,  -1, 100],
       [ -1,  -1,  -1,   0,  -1,  -1],
       [ -1,   0,   0,  -1,   0,  -1],
       [  0,  -1,  -1,   0,  -1, 100],
       [ -1,   0,  -1,  -1,   0, 100]])

In [7]:
# Initialize Q-matrix
Q = np.zeros_like(R) #運用array來存

# Hyperparameters
gamma = 0.8  # Discount factor
learning_rate = 0.5
Q

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [13]:
# Starting state (S3)
start_state = 2
# Goal state (S6)
goal_state = 5
num_episodes = 1000
def get_possible_actions(state):
    return np.where(R[state] >= 0)[0]


for episode in range(num_episodes):
    current_state = start_state
    while current_state != goal_state:
        if(np.random.uniform(0, 1) <= 0.1):
            possible_actions = np.where(R[current_state] != -1)[0]
            action = np.random.choice(possible_actions)
        else:
            action = np.argmax(Q[current_state])
        possible_actions = get_possible_actions(current_state)
        action = np.random.choice(possible_actions)  # Choose a random action

        next_state = action
        reward = R[current_state, action]

        # Q-learning update rule
        Q[current_state, action] = reward + gamma * np.max(Q[next_state])


        current_state = next_state

# Find the optimal path
current_state = start_state
optimal_path = [current_state]
while current_state != goal_state:
    next_state = np.argmax(Q[current_state])
    optimal_path.append(next_state)
    current_state = next_state

print("Optimal path:", optimal_path)
print("Q-matrix:")
Q

Optimal path: [2, np.int64(3), np.int64(1), np.int64(5)]
Q-matrix:


array([[  0,   0,   0,   0,  80,   0],
       [  0,   0,   0,  64,   0, 100],
       [  0,   0,   0,  64,   0,   0],
       [  0,  80,  51,   0,  80,   0],
       [ 64,   0,   0,  64,   0, 100],
       [  0,   0,   0,   0,   0,   0]])